#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Skipping lint-staged for now. Will be properly configured when all branches are merged."
# Uncomment the line below when ready to use lint-staged
# npx lint-staged

