# This workflow is temporarily disabled for the project structure PR
# The full workflow configuration is backed up in _test.yml.bak
# It will be restored in the feature/testing-suite PR

name: Test Suite (Disabled)

on:
  # Workflows will only run when manually triggered
  workflow_dispatch:

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: echo "This workflow is temporarily disabled"
